GET http://localhost:4000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidmFtc2kiLCJpYXQiOjE3MDM1OTI2NjF9.FNRuoaMOOsnSFh1eHzhrF-QzoU9NhDCSjoFkjF7f6Vg

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "name":"vamsi",
    "password":"vamsisony"
}

###